services:
  - type: web
    name: fastapi-economic-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
